sudo: false
language: ruby
cache: bundler
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
before_script:
  - RAILS_ENV=test bundle exec rails db:setup
jobs:
  include:
    - name: "specs"
      script:
        - "bundle exec rails spec"
    - name: "style"
      script:
        - "bundle exec rubocop -v"
        - "bundle exec rubocop"
